### ISSUE TITLE
v1.1.0 and OpenCart 2.0

### ISSUE THREAD

**Issue by syntaxerror** [bambora/checkout-opencart#1]
I wonder if the v1.1.0 release actually has been tested on OC 2.0?

It seems odd that it should work out of the box when we know that OC 2.0 and 2.3+ use different folder structure.

T.ex.:
https://github.com/opencart/opencart/tree/2.0.3.1/upload/admin/controller
vs.
https://github.com/opencart/opencart/tree/2.3.0.0/upload/admin/controller

**Comment by AllanWLie** [comment]
Hi @syntaxerror 

Thank you for informing us. We did only test the new version on Opencart 2.3.x and 3.0.x The supported version infomation on the marketplace and here on Github have now been changed.

Have a nice day.

-Allan
