### ISSUE TITLE
When customer using "Billing (Lindorff)" option in checkout

### ISSUE THREAD

**Issue by Freakshows** [bambora/checkout-opencart#10]
I just had the first customer use the billing option at checkout, it seems amount is captured ok in the dashboard, but the error log gave these lines:

> 2018-02-24 19:16:14 - PHP Notice:  Undefined offset: 0 in /xxxx/catalog/controller/extension/payment/bambora_online_checkout.php on line 135
> 2018-02-24 19:16:14 - PHP Notice:  Trying to get property of non-object in /xxxx/catalog/controller/extension/payment/bambora_online_checkout.php on line 135
> 2018-02-24 19:18:28 - PHP Notice:  Undefined offset: 0 in /xxxx/admin/controller/extension/payment/bambora_online_checkout.php on line 395
> 2018-02-24 19:18:28 - PHP Notice:  Trying to get property of non-object in /xxxx/admin/controller/extension/payment/bambora_online_checkout.php on line 395
> 2018-02-24 19:49:50 - PHP Notice:  Undefined offset: 0 in /xxxx/admin/controller/extension/payment/bambora_online_checkout.php on line 395
> 2018-02-24 19:49:50 - PHP Notice:  Trying to get property of non-object in /xxxx/admin/controller/extension/payment/bambora_online_checkout.php on line 395
> 2018-02-24 19:54:19 - PHP Notice:  Undefined offset: 0 in /xxxx/admin/controller/extension/payment/bambora_online_checkout.php on line 395
> 2018-02-24 19:54:19 - PHP Notice:  Trying to get property of non-object in /xxxx/admin/controller/extension/payment/bambora_online_checkout.php on line 395
> 2018-02-24 19:54:27 - PHP Notice:  Undefined offset: 0 in /xxxx/admin/controller/extension/payment/bambora_online_checkout.php on line 395
> 2018-02-24 19:54:27 - PHP Notice:  Trying to get property of non-object in /xxxx/admin/controller/extension/payment/bambora_online_checkout.php on line 395

**Comment by AllanWLie** [comment]
Hi @Freakshows 

We have corrected the error and made a new release.
https://github.com/bambora/checkout-opencart/releases/latest
or
https://www.opencart.com/index.php?route=marketplace/download&member_token=chshAtMgpETeaPtcyklv4mdJk5chX1hQ&extension_id=31882

Thank you for reporting the issue.

Best regards
Allan
