### ISSUE TITLE
Norwegian language dir name

### ISSUE THREAD

**Issue by Freakshows** [bambora/checkout-opencart#11]
Just a little notice, i think the common directory name used sins it changed from "norsk" or "norwegian" in OC 2.x is **no-nb** _not_ **nb-no**, i have only seen it as no-nb in addons where there is a norwegian at all, i have yet to see it written as nb-no as it is in this release. But kudos for adding norwegian at all :)

:)

**Comment by syntaxerror** [comment]
Well, maybe the "default" in OC extensions/addons should be corrected to follow a common standard (iso) instead of other following on the wrong path?

no-nb is not correct in any way, it's either nb-no or no-no.

After all, OC itself uses en-gb (English - Great Britain), and nb-no (Norwegian Bokmål - Norway) equals to that. Norwegian Nynorsk would be nn-no, Sami se-no etc.

Anyhow, as OC devs and translators seems unable to follow a common path and standard, some would need to check and rename the folders anyway - no mater what's chosen.

;)

**Comment by Freakshows** [comment]
All that is true, and i agree, but it still dont change the fact that it is what it is and no-nb is widely used and users installing this addon should at least be made aware of the difference /me thinks :)

**Comment by syntaxerror** [comment]
I'm not so sure about the widly used, and still it's no standard, so users allready should know they need to be aware of this. In OC 1.5-20 you had "norsk", "norwegian", "nb-no" etc. - same in OC3 :)

Actually it's insane that there is no "official" standard or language packs for OpenCart, and it's also insane that there is 10+ Norwegian language packs, where each and one is "reinventing" the wheel.

**Comment by Freakshows** [comment]
All true :)

**Comment by AllanWLie** [comment]
Hi all,

Thank you for your feedback.

So what should we call the Norwegian language directory and / or should we create two directories for backward compatibility?

Best regards
Allan - Bambora

**Comment by Freakshows** [comment]
Hello

It is widley used as no-nb on opencart, at least for 2.3.0.2, and i think it would be smart to keep it like that, a directory named as norwegian could also be helpfull for as you say backward compatibility in my opinion

**Comment by syntaxerror** [comment]
Actually Freakshows, you should rename that no-nb, and tell the so called translators to do the same.
The language detection in browsers do not recognise it, when they tell people to use it in settings too. I honestly wonder if they have done anything else than releasing the work of someone else, after renaming it. Testing and understanding is lacking for sure, nobody should be using no-nb ever.

I would rather outline this mistake in the readme, and encourage users and translators to get it fixed.

**Comment by Freakshows** [comment]
As i have said before, i am just telling whats out there, i have no plans to tell anyone anything, that is way to much work and involment :) as also said before i do agree with you, but having the "correct" one just for this mod will cause a lot of unnessesary support calls to bambora i think. and its not an issue for me no matter what the dir name is, i know about this issue :)

**Comment by syntaxerror** [comment]
Still you're telling it here. ;)

Here's the language codes recognised by latest Firefox by default. Your no-nb shop wouldn't be recognised, and might display English for the whole shop instead if it's still available ...

![skjermdump fra 2018-07-25 10-47-38](https://user-images.githubusercontent.com/858132/43186747-4a57754e-8ff8-11e8-9200-0713fdd93ae0.png)

Btw! Also Bambora uses nb-no in the api/module, without any "fallback", so it's natural to keep that and don't bother about others mistakes and "stupidity".

Bambora wouldn't get more support calls for this, not more than when there's no language files included at least. Still, renaming or adding duplicates isn't the way to go, then it's better to outline it in the docs to "educate" all needing it.

**Comment by Freakshows** [comment]
Yeah, i mean go for it, its not my issue anyway :)

**Comment by syntaxerror** [comment]
So we kind of agree then, that it's better to add to the docs to educate the users, so they get their shop correctly configured? Also since the payment window would use the same faulty language code from the settings, and wouldn't find a match on no-nb: https://github.com/bambora/checkout-opencart/blob/3f85a3dda60c0586f6d457e98d7722eb95777c96/upload/catalog/controller/extension/payment/bambora_online_checkout.php#L237

**Comment by Freakshows** [comment]
you start educating, i will get the popcorn :)

**Comment by syntaxerror** [comment]
Maybe you missed the point, but if you have mistakes in your language setup, you'll get English somewhere anyway - like in the payment window. Having a duplicate with a non valid name doesn't fix that.

Educating those who doesn't want to learn, yeah, I agree it would be impossible. But still, if anyone don't care to read docs or listen to facts it's their loss.

**Comment by AllanWLie** [comment]
Hi again,

For now we will keep it the way it is.

Thank you for your interest and have a nice day.

Best regards
Allan - Bambora
