### ISSUE TITLE
When using Billing option, the ID for shipping in the invoice seems strange?

### ISSUE THREAD

**Issue by Freakshows** [bambora/checkout-opencart#12]
No errors are generated but it seems strange to use some sort of code name for the shipping ID in the generated invoice? (see attachment). It shows the same in invoice at Lindorff Access.
![capture](https://user-images.githubusercontent.com/13005141/38038743-f9bff7d6-32ab-11e8-8581-88d5b231ee02.PNG)

**Comment by syntaxerror** [comment]
This is the shipping code, saved in orders table to identify the shipping module and selection / table used.

I guess it's used because shipping options doesn't have any SKU / Product Number, but it would probably be better to just hardcode a 'SHIPPING' SKU in the module instead. Same for vouchers and other 'totals'.

**Comment by syntaxerror** [comment]
Seems like the following lines should be changed:
https://github.com/bambora/checkout-opencart/blob/master/upload/catalog/controller/extension/payment/bambora_online_checkout.php#L354
`$shipping['id'] = 'SHIPPING';`
https://github.com/bambora/checkout-opencart/blob/master/upload/catalog/controller/extension/payment/bambora_online_checkout.php#L385 
`$coupon['id'] = 'COUPON';`
https://github.com/bambora/checkout-opencart/blob/master/upload/catalog/controller/extension/payment/bambora_online_checkout.php#L405
`$voucher['id'] = 'VOUCHER';`

**Comment by Freakshows** [comment]
Yeah something like that, but even better if it picked up the actual shipping method used, like i.e "Servicepakke" , "Pakke i postkassen", Free shipping and so on.

**Comment by syntaxerror** [comment]
That is already there, in the name (title) - this is just the "SKU".
Would not make sense to have 'Servicepakke' on both lines. ;)

Only useful improvement I can see in this, is to add translation of the "SKU" for the language in use on the order (Shipping -> Levering etc).

**Comment by Freakshows** [comment]
Ahh yeah, sorry my misstake :)

**Comment by Freakshows** [comment]
Have you tested the module with those lines you mention changed?

**Comment by AllanWLie** [comment]
Hi all,

Thank you for your feedback. We will look in to this in a future release.

Best regards
Allan - Bambora

**Comment by AllanWLie** [comment]
Hi @Freakshows and @syntaxerror 

We have now "hard coded" the shipping, coupon and voucher id's (offcause based on translations) and it is released here: https://github.com/bambora/checkout-opencart/releases/latest

@syntaxerror could you verify the Norwegian translations. 

Thank you both.

Best regards
Allan - Bambora

**Comment by syntaxerror** [comment]
Will do, thanks Allan. :)
