### ISSUE TITLE
Refund Lindorff

### ISSUE THREAD

**Issue by Freakshows** [bambora/checkout-opencart#16]
Hi
When trying to partial refund a Lindorff transaction it fails, Opencart does not register any errors but when checking Bambora Merchant web the refund shows:

> Refund failed
> The partial refund attempt failed.Initiated by OpenCart/2.3.0.2 Module/1.2.3

Freakshows

**Comment by AllanWLie** [comment]
@Freakshows 
Is this still an issue ? If so please contact support@bambora.com and describe the issue and add your merchant information.

Best regards
Allan - Bambora
