### ISSUE TITLE
BankID issues

### ISSUE THREAD

**Issue by Freakshows** [bambora/checkout-opencart#20]
Whould it be possible to get a live check of BankID in the payment window? 

Customers are trying repetadly to generate a order not knowing that there is problems with BankID and then generating loads of work and support calls for us.

**Comment by AllanWLie** [comment]
Hi @Freakshows 
It is currently not possible to get a live / status check for BankID in the payment window and as far as I know there are not any plans of adding it but I have written it down as a feature request. 

Best regards
Allan Lie - Bambora Online A/S
