### ISSUE TITLE
An error occured when trying to open the payment window. Reason: Ogiltig webbadresse

### ISSUE THREAD

**Issue by tlombert** [bambora/checkout-opencart#21]
Hi

Starting to test Bambora Checkout in a Opencart 3.0.3.2. I gets this error then I try to do a test purchase.

"An error occured when trying to open the payment window. Reason: Ogiltig webbadresse"

Using the last version found here.

**Comment by syntaxerror** [comment]
You should rather contact Bambora support than spamming the issues tracker at GitHub, with something that clearly isn't a bug in the module/code. It's just your domain who isn't valid for that account you're trying to use, so better contact support and they will explain it to you in details.

Or you could just also create another test account for your test domain. ;)

**Comment by tlombert** [comment]
Thanks! I have send a question to the support to. 
I also start to think they missed something with the domain. But maybe a good idea to have a more informative text about this problem/error.. ;)

**Comment by syntaxerror** [comment]
> But maybe a good idea to have a more informative text about this problem/error.. ;)

That I can agree to, and it should also be mentioned in the DOCs/FAQs.

**Comment by tlombert** [comment]
And as a end comment, it was the domain. We have a multistore setup, and they have "setup" a secondary store in there system. If I try from that domain it works as it should. Thanks again for the reply.
