### ISSUE TITLE
Wrong link in Order History/#tab-bambora_online_checkout

### ISSUE THREAD

**Issue by tlombert** [bambora/checkout-opencart#22]
Hi

In the last version found here, the link to the "Bambora Online Merchant Administration" is broken inside Order History tab. There it goes to https://admin.epay.eu/Account/Login, and for me it stops there..

My admin login is; https://auth.bambora.com/account/login, but maybe there are others to..

It's a small thing, but nether less should be right or check the link so it works..

<img width="1179" alt="Skärmavbild 2020-10-26 kl  21 44 58" src="https://user-images.githubusercontent.com/34110406/97227508-df7e4780-17d5-11eb-9742-c4b2f4caa98b.png">

Best Regards
Thomas

**Comment by sessan** [comment]
@tlombert Hi! 
This issue is fixed in the latest update of our plugin. The link now point to https://merchant.bambora.com/auth/signin

Best Regards
Jessica Björkäng - Bambora Online
