### ISSUE TITLE
GPL license violations

### ISSUE THREAD

**Issue by syntaxerror** [bambora/checkout-opencart#3]
OpenCart, and most systems you have modules for, are licensed under GPLv3

Your modules also uses a lot of OpenCart (or other carts) code and functions, and therefor considered to be derivative works, and is then also required to use GPLv3 license.

Thus the lines telling people they can't modify the modules would be a violation of the GPL license: https://github.com/bambora/checkout-opencart/blob/master/upload/catalog/controller/extension/payment/bambora_online_checkout.php#L5

Also there is no logic in releasing them as open code at GitHub, and at the same time restricting people to contribute to, and improve the code - reusing and forking. That will only hold back the growth and numbers of system being integrated.

Some useful info:
https://www.gnu.org/licenses/gpl-faq.html
https://wordpress.org/news/2009/07/themes-are-gpl-too/

**Comment by AllanWLie** [comment]
Hi @syntaxerror 

Thank you for pointing this out. 

I have added it to our backlog for our modules.

Have a nice day.

-Allan
