### ISSUE TITLE
Orderline regarding Shipping is not passing 

### ISSUE THREAD

**Issue by KiaEsh** [bambora/checkout-opencart#30]
We have upgraded our Opencart store to OC 3.0.x.x_Maintenance branch which can work with PHP 8.0. 
https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance

It was a fresh installation. V1.4.4 does not fetch orderline regarding Shipping. It does not show shipping price as separated line when you go to Bambora payment module. So all attempts by customers to place orders via Wally's invoice will be rejected. I tested it both on default Opencart checkout and journal Quick checkout with the same result. I have found this issue few days ago. This issue has cost us many customers since we have updated to v1.4.4 around 16 January this year. It is a serious issue and must be fixed as soonest!

**Comment by sessan** [comment]
Please upgrade to 1.5.0
