### ISSUE TITLE
Flooded error log

### ISSUE THREAD

**Issue by Freakshows** [bambora/checkout-opencart#7]
Every time i enter the module config in admin i get this events in the log file, same amount of entrys if i click save inside the module admin. OC 2.3.0.2

> 2018-02-06 18:59:15 - PHP Notice:  Undefined variable: breadcrum in /xxxx/admin/view/template/extension/payment/bambora_online_checkout.tpl on line 14
> 2018-02-06 18:59:15 - PHP Notice:  Undefined variable: breadcrum in /xxxx/admin/view/template/extension/payment/bambora_online_checkout.tpl on line 14
> 2018-02-06 18:59:15 - PHP Notice:  Undefined variable: breadcrum in /xxxx/admin/view/template/extension/payment/bambora_online_checkout.tpl on line 14
> 2018-02-06 18:59:15 - PHP Notice:  Undefined variable: help_window_id in /xxxx/admin/view/template/extension/payment/bambora_online_checkout.tpl on line 105
> 2018-02-06 18:59:15 - PHP Notice:  Undefined variable: entry_windowid in /xxxx/admin/view/template/extension/payment/bambora_online_checkout.tpl on line 107

**Comment by syntaxerror** [comment]
To fix it temporary, take a look at https://github.com/bambora/checkout-opencart/pull/8/files

**Comment by Freakshows** [comment]
Thanks, tested ok

**Comment by AllanWLie** [comment]
Hi @Freakshows 

The changes have now been added to the master branch, and will soon be released.

Thank you @syntaxerror 

Best regards
Allan
